const Item=[
    {
     img:"./image/img1.jpeg"
    },
    {
     img:"/image/img2.jpeg"
    },
    {
     img:"/image/img3.jpeg"
    },
    {
     img:"/image/img4.jpeg"
    },
    {
     img:"/image/img5.jpeg"
    },
    {
     img:"/image/img6.jpeg"
    },
    {
     img:"/image/img7.jpeg"
    },
    {
     img:"/image/img8.jpeg"
    },
    {
     img:"/image/img9.jpeg"
    },
    {
        img:"/image/img10.jpeg"
       },
       {
        img:"/image/img11.jpeg"
       },
       {
        img:"/image/img12.jpeg"
       },
       {
        img:"/image/img13.jpeg"
       },
       {
        img:"/image/img14.jpeg"
       },
       {
        img:"/image/img15.jpeg"
       },
       {
        img:"/image/img16.jpeg"
       },
       {
        img:"/image/img17.jpeg"
       },
       {
        img:"/image/img18.jpeg"
       },
       {
        img:"/image/img19.jpeg"
       },
       {
        img:"/image/img20.jpeg"
       },
       {
        img:"/image/img21.jpeg"
       },
       {
        img:"/image/img22.jpeg"
       },
       {
        img:"/image/img23.jpeg"
       },
       {
        img:"/image/img24.jpeg"
       },
       {
        img:"/image/img25.jpeg"
       },
       {
        img:"/image/img26.jpeg"
       },
       {
        img:"/image/img27.jpeg"
       },
       {
        img:"/image/img28.jpeg"
       },
       {
        img:"/image/img29.jpeg"
       },
       {
        img:"/image/img30.jpeg"
       },
       {
        img:"/image/img31.jpeg"
       },
       {
        img:"/image/img32.jpeg"
       },
       {
        img:"/image/img33.jpeg"
       },
       {
        img:"/image/img27.jpeg"
       },
       
      
 ]
 
 export default Item